config/routes.rb
Blog::Application.routes.draw do
  namespace :admin do
    resources :posts do
      resources :links
    end
  end
  
  

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :links
  
  validates :title,  :presence  => true, :uniqueness => true
  validates :entry,  :presence  => true
  validates :author, :presence  => true
end
  

app/controllers/admin/links_controller.rb
class Admin::LinksController < ApplicationController
  before_filter :get_current_post
  before_filter :get_current_link, :only => [:show, :edit, :update, :destroy]

  def index
    @links = @post.links
  end

  def show
  end

  def new
    @link  = @post.links.build
  end

  def create
    @link  = @post.links.build(params[:link])
    if @link.save
      redirect_to admin_post_links_path(@post)
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @link.update_attributes(params[:post])
      redirect_to admin_post_links_path(@post)
    else
      render :action => :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to admin_post_links_path(@post)
  end

protected
  def get_current_post
    @post = Post.find(params[:post_id])
  end

  def get_current_link
    @link = @post.links.find(params[:id])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_filter :get_current_post, :only => [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end
  
  def new
      @post  = Post.new
  end
  
  def create
      @post  = Post.new(params[:post])
      if @post.save
        redirect_to admin_posts_path
      else
        render :action => :new
      end
  end
  
  def edit
      @post  = Post.find(params[:id])
  end

  def update
      if @post.update_attributes(params[:post])
        redirect_to admin_posts_path
      else
        render :action => :edit
      end
  end
  
  def show
    @links = @post.links
  end
  
  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end
  
  protected
    def get_current_post
      @post  = Post.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/admin/links_helper.rb
module Admin::LinksHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/links/_form.erb
<div class="field">
  <%= f.label :url %> <br />
  <%= f.text_field :url %>
</div>

<div class="field">
  <%= f.label :description %> <br />
  <%= f.text_area :description %>
</div>

app/views/admin/links/_link.erb
<li>
  <h3><%=  link_to link.url, link.url, :target => "_blank" %></h3>
  <div class="except"><%= link.description %></div>
  <div class="actions">
    <%= link_to 'Edit', [:admin, @post, link] %>
    <%= link_to 'Remove', [:admin, @post, link], :method => :delete, 
         :confirm => "Are you sure?" %>
  </div>
</li>

app/views/admin/links/edit.html.erb
<h2>Editing Link "<%= @Link.url %>"</h2>

<div class="form-box">
  <% form_for [:admin, @post, @link] do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>

    <div class="actions">
      <%= f.submit :update %>
      or
      <%= link_to 'cancel', admin_post_links_path %>
    </div>
  <% end %>
</div>

app/views/admin/links/index.html.erb
<h2>Listing Links of Post</h2>

<div class="new-record">
  <%= link_to 'Add new Link', new_admin_post_link_path %>
</div>

<ul class="list">
  <%= render @links %>
</ul>

app/views/admin/links/new.html.erb
<h2>Add New Link</h2>

<div class="form-box">
  <%= form_for [:admin, @post, @link] do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    
    <div class="actions">
      <%= f.submit :save %>
      or
      <%= link_to 'cancel', admin_posts_path %>
    </div>
  <% end %>
</div>

app/views/admin/links/show.html.erb
<ul class="item ">
	<%= render @link %>
</ul>

app/views/admin/posts/_form.erb
<div class="field">
  <%= f.label :title %> <br />
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :entry %> <br />
  <%= f.text_area :entry %>
</div>

<div class="field">
  <%= f.label :author %> <br />
  <%= f.text_field :author %>
</div>

app/views/admin/posts/_post.erb
<li>
  <h3><%= link_to post.title, [:admin, post] %></h3>
  <div class="excerpt"><%= truncate(post.entry, :length => 90) %></div>
  <div class="actions">
    <%= link_to 'Edit', [:edit, :admin, post] %>
    <%= link_to 'Remove', [:admin, post], :method => :delete, 
         :confirm => "Are you sure?" %>
  </div>
</li>

app/views/admin/posts/edit.html.erb
<h2>Editing Post "<%= @post.title %>"</h2>

<div class="form-box">
  <% form_for [:admin, @post] do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>

    <div class="actions">
      <%= f.submit :update %>
      or
      <%= link_to 'cancel', admin_posts_path %>
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<h2>Listing Posts</h2>

<div class="new-record">
  <%= link_to 'Add new Post', new_admin_post_path %>
</div>

<ul class="list">
  <%= render @posts %>
</ul>

app/views/admin/posts/new.html.erb
<h2>Add New Post</h2>

<div class="form-box">
  <%= form_for [:admin, @post] do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    
    <div class="actions">
      <%= f.submit :save %>
      or
      <%= link_to 'cancel', admin_posts_path %>
    </div>
  <% end %>
</div>

app/views/admin/posts/show.html.erb
<ul class="item ">
  <li>
	<div class="actions">
      <%= link_to 'Edit', [:edit, :admin, @post] %> |
      <%= link_to 'Remove', [:admin, @post], :method => :delete, 
           :confirm => "Are you sure?" %> |
	  <%= link_to 'Back to listing page', admin_posts_path %>
	
    <h3><%= link_to @post.title, [:admin, @post] %></h3>
    <div class="excerpt"><%= @post.entry %></div>
  </li>
  <hr>
  <%= link_to 'add link', new_admin_post_link_path(@post) %>

<div class="form-box">
	<ul class="list">
	   <%=render @links %>
	 </ul>
</div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>